### ISSUE TITLE
First spec for Dog class should use create method, not new method

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-students/sinatra-mvc-file-structure-v-000#44]
Hi there!

The first spec for the Dog class currently reads:

describe 'Dog class' do 
    it 'can create a dog with attributes on initialization' do 
      Dog.new("rudolph", "mastiff", 2)
      expect(Dog.all.count).to eq (1)
    end
    ....
end

it seems like it should read:

describe 'Dog class' do 
    it 'can create a dog with attributes on initialization' do 
      Dog.create("rudolph", "mastiff", 2)
      expect(Dog.all.count).to eq (1)
    end
    ....
end

so that the dog is saved into all and will be visible.

**Comment by vicfriedman** [comment]
Hey @DakotaLMartinez thanks so much for opening this PR. Next time, please make sure to open PR's on the canonical of the repo - github.com/learn-co-curriculum/sinatra-mvc-file-structure.

This lab actually doesn't have a database, so we can use `.create`. I'm going to go ahead and close this PR.
